title: Fusion
menus:
  header:
    - label: À propos
      href: /
    - label: Contact
      href: /
    - label: Facebook
      href: https://www.facebook.com/fusionatalante/
    - label: Twitter
      href: https://www.twitter.com/fusionatalante/
  nav:
    - label: Livres
      href: /fr/page/livres
    - label: Auteurs
      href: /fr/page/auteurs
    - label: Traducteurs
      href: /
    - label: Actualités
      href: /
  footer:
    - label: Accueil
      href: /
    - label: Livres
      href: /
    - label: Auteurs
      href: /
    - label: Traducteurs
      href: /
    - label: Actualités
      href: /
    - label: Contact
      href: /
    - label: À propos
      href: /
    - label: Mentions légales
      href: /
