title: Fusion
menus:
  header:
    - label: À propos
      href: /fr/page/a-propos
    - label: Contact
      href: /fr/page/contact
    - label: Facebook
      href: https://www.facebook.com/fusionatalante/
    - label: Twitter
      href: https://twitter.com/CarolinedeBene1
  nav:
    - label: Livres
      href: /fr/page/livres
    - label: Auteurs
      href: /fr/page/auteurs
    - label: Traducteurs
      href: /fr/page/traducteurs
    - label: Actualités
      href: /fr/page/actualites
  footer:
    - label: Accueil
      href: /
    - label: Livres
      href: /fr/page/livres
    - label: Auteurs
      href: /fr/page/auteurs
    - label: Traducteurs
      href: /fr/page/traducteurs
    - label: Actualités
      href: /fr/page/actualites
    - label: Contact
      href: /
    - label: À propos
      href: /fr/page/a-propos
    - label: Mentions légales
      href: /fr/page/mentions-legales
